version: "3.5"

networks:
  sonarnet:

volumes:
  sonarqube_conf:
  sonarqube_data:

services:
  sonarqube:
    image: mc1arke/sonarqube-with-community-branch-plugin:9.0-community
    container_name: sonarqube
    ports:
      - 9000:9000
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://host.docker.internal:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=postgres
      - SONARQUBE_JDBC_PASSWORD=P@ssw0rd!
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
    restart: unless-stopped
