version: "3.5"

networks:
  sonarnet:

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

services:
  sonarqube:
    image: sonarqube:10.0.0-community
    # image: mc1arke/sonarqube-with-community-branch-plugin:9.9-community
    ports:
      - 9000:9000
    networks:
      - sonarnet
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://host.docker.internal:5433/sonarqube
      - SONAR_JDBC_USERNAME=postgres
      - SONAR_JDBC_PASSWORD=P@ssw0rd!
    volumes:
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - ./conf/sonar.properties:/opt/sonarqube/conf/sonar.properties
      - ./files/sonarqube-community-branch-plugin-1.15.0-SNAPSHOT.jar:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.15.0-SNAPSHOT.jar
    restart: unless-stopped
    mem_reservation: 2G
    mem_limit: 3G
