version: "3.5"

services:
  rabbitmq:
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 7002:15672
    environment:
      - RABBITMQ_MANAGEMENT_DEFAULT_USER:admin
      - RABBITMQ_MANAGEMENT_DEFAULT_PASS:P@ssw0rd!
    image: rabbitmq:3.8.5-management
