version: "3.5"

services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    restart: unless-stopped
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ~/.docker_volumes/rabbitmq:/var/lib/rabbitmq/mnesia
    ports:
      - 5672:5672
      - 7002:15672
