apiVersion: v1
data:
  labs-barakimam-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIBuzCCAWGgAwIBAgIQRgpbIrEsrLVXUYP69qrfEDAKBggqhkjOPQQDAjA8MRgw
    FgYDVQQKEw9CYXJhayBMb2NhbGhvc3QxIDAeBgNVBAMTF0JhcmFrIExvY2FsaG9z
    dCBSb290IENBMB4XDTIyMDIxNjE5NDMzMVoXDTMyMDIxNDE5NDMzMVowPDEYMBYG
    A1UEChMPQmFyYWsgTG9jYWxob3N0MSAwHgYDVQQDExdCYXJhayBMb2NhbGhvc3Qg
    Um9vdCBDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABK45cMsQgLnjlim2kyEp
    ZxkMizU1V1j7vNtnYhdt1hvOYKF3806A8/RJ9xIjzwzkyo7ZCMI5G8JOGNgY7CWO
    CZWjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0GA1Ud
    DgQWBBRxao2tlSSuWUDXFyWilh31k5ASFTAKBggqhkjOPQQDAgNIADBFAiEAqrrE
    CCvgiW3Khrkkp1bBg4aW9ewjW2sM+60TMR9GTa8CIGbEWi+kjlccYtg0UEBZzgHN
    T32q6Z8dpLu+KY45KEyG
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: dev-localhost-ca-root
  namespace: loft