apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-dev-localhost
  namespace: loft
spec:
  secretName: dev-localhost-tls
  commonName: "dev.localhost"
  issuerRef:
    kind: ClusterIssuer
    name: dev-localhost-ca
  dnsNames:
  - "*.dev.localhost"
  - "dev.localhost"
