
resources:
  requests:
    cpu: "1000m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "768Mi"

# --set="resources={request: { cpu: '1000m', memory: '256Mi' }, limits: { cpu: '2000m', memory: '1.5Gi' }}"
