version: "3.5"

volumes:
  mssql_data:
  mysql_data:
  postgres_data:

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd!
      - TZ=Africa/Lagos
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql
    # cpus: 2
    # mem_reservation: 256m
    # mem_limit: 2.5g

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd!
      - TZ=Africa/Lagos
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    cpus: 1
    mem_reservation: 256m
    mem_limit: 1g

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: P@ssw0rd!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    cpus: 1
    mem_reservation: 128m
    mem_limit: 768m

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8003:8080
    cpus: 0.5
    mem_reservation: 64m
    mem_limit: 256m

networks:
  default:
    external:
      name: homelab
