version: "3.5"

volumes:
  mysqlvolume:

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd!
      - TZ=Africa/Lagos
    ports:
      - 3306:3306
    volumes:
      - mysqlvolume:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8003:8080
