version: "3.5"

volumes:
  data:

services:
  minio:
    image: minio/minio:RELEASE.2021-03-10T05-11-33Z
    restart: always
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - TZ=Africa/Lagos
    ports:
      - 7000:9000
    volumes:
      - data:/data
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    cpus: 0.5
    mem_reservation: 256m
    mem_limit: 512m

  console:
    image: minio/console
    restart: unless-stopped
    environment:
      - CONSOLE_PBKDF_PASSPHRASE=console_salt
      - CONSOLE_PBKDF_SALT=console_salt
      - CONSOLE_ACCESS_KEY=console
      - CONSOLE_SECRET_KEY=secretforminioconsole0123456789
      - CONSOLE_MINIO_SERVER=http://minio:9000
      - TZ=Africa/Lagos
    ports:
      - 7001:9090
    cpus: 0.5
    mem_reservation: 256m
    mem_limit: 512m
    entrypoint: ["./console", "server"]
