version: "3.5"

services:
  redis:
    image: redis/redis-stack
    volumes:
      - ~/.docker_volumes/redis:/data
      - ./redis-stack.conf:/redis-stack.conf
    ports:
      - 6379:6379
      - 8001:8001
    restart: unless-stopped
    cpus: 0.5
    mem_reservation: 128m
    mem_limit: 256m
