version: "3.5"

volumes:
  data:

services:
  redis:
    container_name: redis_local
    image: redis:latest
    volumes:
      - data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    restart: unless-stopped
    cpus: 0.5
    mem_reservation: 128m
    mem_limit: 256m
