version: "3.5"

services:
  redis:
    image: redis:6-alpine3.17
    volumes:
      - ~/.docker_volumes/redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    restart: unless-stopped
    cpus: 0.5
    mem_reservation: 128m
    mem_limit: 256m
